[package]
name = "foodb-api"
version = "0.1.0"
authors = ["Joshua Gevirtz <joshgev@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
